services:
  db:
    image: postgres:14
    env_file:
      - .env # Load environment variables from .env file
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine # Use a specific version
    restart: unless-stopped
    env_file:
      - .env # Load environment variables from .env file
    command: redis-server --save 60 1 --loglevel warning # Persist data every 60s if at least 1 key changed
    # If you set a password in .env (REDIS_PASSWORD), uncomment and set it here:
    # command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
    ports:
      - "6379:6379" # Expose Redis on port 6379